- www.foia.gov/_sass/modules/_buttons.scss
* Tweaks the usa-button-primary-alt background color default and hover.
* Adds a usa-button-small for buttons with default weight text.
> FOIA-268: Update button styles to match mockups.

- www.foia.gov/data.html
Removes front matter that included legacy scripts and styles in
www.foia.gov/data.html.
> FOIA-297: Remove legacy frontmatter in data.html.

- www.foia.gov/results.html
- www.foia.gov/results/index.html
Adds a results.html page at www.foia.gov/results.html.
> Foia-298: Create page shell for results.html.

- bin/git-deploy.sh
Reverts acquia-pso/foia.gov-enhancements#8
> FOIA-000: Revert "FOIA-000: Adds CI deployment repo."

- js/components/foia_report_form_section_three.jsx
- js/pages/annual_report_data.jsx
- www.foia.gov/_sass/_modules.scss
- www.foia.gov/_sass/modules/_checkbox_list.scss
- www.foia.gov/_sass/modules/_inline_list.scss
* Adds a section three component.
* Adds an inline list sass module to display list items
inline with a separator.
* Adds a checkbox list sass module to add padding
around checkbox list items when displayed in a grid.
* Adds section three component to the AnnualReportDataPage.
> Foia-266: Style section three of report form.

- docs/annual-report-data-app.md
- js/components/foia_report_form_section_three.jsx
- js/components/foia_report_form_section_two.jsx
- js/components/foia_tooltip.jsx
- www.foia.gov/_sass/modules/_tooltip.scss
- Sets Tooltip font styles so they aren't inherited by parent.
- Adds z-index to Tooltip so it overlays nav.
- Changes propType from string to object to allow markup.
> FOIA-322: Tooltip text bugfix.

- www.foia.gov/api/annual-report-form/report_data_map.json
@bemarlan here is the completed JSON file.
> FOIA-314: Complete rest of static json report field file.

- www.foia.gov/api/annual-report-form/report_data_map.json
@bemarlan - there may be things that are updated elsewhere, but I made all the changes I found.
> FOIA-315: Fixes to the report data map JSON file.

- js/components/foia_report_form_section_two.jsx
- js/stores/annual_report_data_form.js
@bemarlan here are the two changes we talked about.
> FOIA-319: Post merge fixes

- js/pages/annual_report_data.jsx
- www.foia.gov/_sass/_modules.scss
- www.foia.gov/_sass/modules/_results_loading.scss
- www.foia.gov/_sass/modules/_results_page_header.scss
- www.foia.gov/_sass/modules/_results_toolbar.scss
- www.foia.gov/_sass/modules/_spinner.scss
- www.foia.gov/_sass/theme/_annual_report_data_page.scss
I also added a simple loading animation in this PR so it doesn't look like the screen freezes after clicking submit.
> FOIA-299: Adding Results Headings.

- js/actions/report.js
- js/annual_report_data.jsx
- js/components/foia_report_submit.jsx
- js/pages/annual_report_data.jsx
- js/stores/annual_report.js
- js/stores/annual_report_data_form.js
@bemarlan The first commit should contain only the code I added to support clearing the form. The second commit is supposed to be everything else. Hopefully I split it properly.
We are now using a router, and the URL does change, but still begins with `data.html`. I couldn't get the browser history to actually do anything if the url didn't change.
> FOIA-338: Browser back button

- js/pages/annual_report_data.jsx
- www.foia.gov/_sass/modules/_foia_report_results_table.scss
- www.foia.gov/_sass/theme/_annual_report_data_page.scss
**Important:** See my comments in [FOIA-331](https://acquiaps.atlassian.net/browse/FOIA-331) and let me know if you want to talk through anything before merging.
> FOIA-331: Print Styles for results page.

- js/pages/annual_report_data.jsx
Adds classes back in that were lost in merge regression.
> FOIA-333: Hiding results buttons for print.

- js/components/foia_report_data_type_filter.jsx
* Allows data filter fields to span the width of the modal.
> FOIA-339: Fix uncentered modal content.

- docs/annual-report-data-app.md
- js/components/foia_report_data_type_filter.jsx
- js/components/foia_report_form_checkbox_widget.jsx
- js/components/foia_report_form_section_one.jsx
- js/components/foia_report_form_section_three.jsx
- js/components/foia_report_form_section_two.jsx
- js/components/foia_tooltip.jsx
- js/components/report_agency_component_filter.jsx
- js/components/uswds_select_widget.jsx
- js/stores/annual_report.js
- www.foia.gov/_includes/header.html
- www.foia.gov/_layouts/base.html
- www.foia.gov/_sass/_base.scss
- www.foia.gov/_sass/base/_utilities.scss
- www.foia.gov/_sass/mixins/_touch_safe.scss
- www.foia.gov/_sass/modules/_buttons.scss
- www.foia.gov/_sass/modules/_foia_report_results_table.scss
- www.foia.gov/_sass/modules/_form_group.scss
- www.foia.gov/_sass/modules/_inline_list.scss
- www.foia.gov/_sass/modules/_tooltip.scss
- www.foia.gov/index-es.html
- Fixes one accessibility error reported by Wave and Lighthouse.
- Fixes keyboard navigation issues discovered in manual testing.
- Adds touch-safe zones to links and checkboxes.
This PR does not complete FOIA-325. This code needs to be available on UAT for additional screen reader testing.
> FOIA-325: Accessibility launch readiness audit

- js/util/foia_annual_report_filter_utilities.js
Fixes a bug that prevents some filters from transforming to overall filters when required.
> FOIA-358: Fix bug preventing filtering on overall.

- js/components/foia_report_submit.jsx
- js/components/report_agency_component_typeahead.jsx
- js/stores/annual_report.js
- www.foia.gov/_layouts/base.html
- www.foia.gov/_sass/base/_typography.scss
- www.foia.gov/_sass/modules/_form_group.scss
- www.foia.gov/_sass/modules/_tooltip.scss
- Updates for screen readers
- Fixes Tooltip positioning issues for Safari
- Fixes results URL to only get added when viewing results and not for downloading CSV results
- Resets focus on body when results page loads
> FOIA-325: Accessibility launch readiness audit.

- js/components/foia_report_results_table.jsx
Better scroll when tabbing via headers.
> FOIA-364: Fix scrolling tables via tab focus.

- js/components/foia_report_results_table.jsx
Reverts acquia-pso/foia.gov-enhancements#100
> Revert "FOIA-364: Fix scrolling tables via tab focus."

- js/stores/annual_report.js
- www.foia.gov/_sass/modules/_foia_report_results_table.scss
- www.foia.gov/_sass/modules/_glossary.scss
- Fixes focus styling on table headers in IE
- Fixes sort icon display for table headers in IE
- Prevents glossary from printing on iOS devices (Safari, Chrome and Firefox Dark)
> FOIA-364: Cross Browser Testing Bug Fixes
